### ISSUE TITLE
Object and Method Names Should More Closely Match PCRE2 Names

### ISSUE THREAD

**Issue by jpbro** [jpbro/VbPcre2#10]
As per discussion in this issue: [link][https://github.com/jpbro/VbPcre2/issues/6]

The VBPCRE2 Object and Method names should be updated to more closely match PCRE2.

For example, all class names currently start with CPcre*, but these should be changed to CPcre2*

Public methods like Execute and Replace should more closely match the PCRE2 method names (so Match and Substitute would be more appropriate).

**Comment by dragokas** [comment]
No objections.
Just, I think, lower case "c" is better: cPcre2 e.t.c.

**Comment by jpbro** [comment]
Closed by the following commits:

https://github.com/jpbro/VbPcre2/commit/6e28a56b75bc269348bb06338f911823b742bbf7
https://github.com/jpbro/VbPcre2/commit/f424fef5188b5b45fac1a182bd94381317df94d5
https://github.com/jpbro/VbPcre2/commit/896a1264d035d7311fe43280fa11857918ba46ba
