### ISSUE TITLE
Feature: FirstIndex of CPcreMatch

### ISSUE THREAD

**Issue by dragokas** [jpbro/VbPcre2#12]
Just a last one (I think) VBS-like feature request to Pcre: to add 'FirstIndex' property to 'CPcreMatch'. It have to point to position in original string of match that was found.

Something like pa_OvectorArray() for SubMatches, but for Match.
I didn't see is it can be done easily, so it is still a subject of discussion.
Anyway, I would like to know how to add this feature myself.

**Comment by jpbro** [comment]
Thanks for the feature request @dragokas - this has been implemented in the latest commit.

**Comment by dragokas** [comment]
> has been implemented

Not sure, is it already committed (don't see) or planned to be?

I finished my portable proxy-wrapper, so it is the last feature to be implemented for a full mimic of VBScript.Regexp if first one is failed. Will be ready to post it as soon as add this feature.

UPD. Ohh, didn't see a commit.
It's very nice you are implemented this together with LastIndex and Length properties.
