### ISSUE TITLE
Brackets [] in enum

### ISSUE THREAD

**Issue by dragokas** [jpbro/VbPcre2#14]
I know that [ ] used when you want to use reserved keyword in enum.
_PCRE_RC_ERROR_FIRST is not reserved ?

What is a benefit here:
```
Private Enum PCRE_ReturnCode
   ...
   [_PCRE_RC_ERROR_FIRST] = -1
   [_PCRE_RC_ERROR_LAST] = -62
End Enum
```

P.S. Do you not mind that I am asking theoreticall question here?

**Comment by jpbro** [comment]
I don't mind at all! In this case, the `[_*]` (note the underscore) makes the enum values hidden from intellisense - it's an undocumented trick that I found somewhere on the Internet a  long time ago (sorry I don't have the source). This way the user only sees the main enum names in intellisense and not the hidden ones that are only used internally for looping through all of the enum values for example.

**Comment by dragokas** [comment]
Nice, interesting. Thank you.
