### ISSUE TITLE
Error checking in SubMatchValue()

### ISSUE THREAD

**Issue by dragokas** [jpbro/VbPcre2#17]
"Invalid procedure call or argument".

ma_Ovector returns -1, when:

l_SubjectText = "Wyzo"
l_Regex = "(Manager)|^((copy of )?(" & "MX5|Wyzo" & "))$"

**Comment by jpbro** [comment]
Thanks for reporting this - it appears to be fixed as a result of work completed for  https://github.com/jpbro/VbPcre2/issues/16
