### ISSUE TITLE
Create ActiveX DLL Using PCRE2 Classes

### ISSUE THREAD

**Issue by jpbro** [jpbro/VbPcre2#20]
The cPcre2* classes should all be moved to an ActiveX DLL as it appears that public object/method names have stabilized.

**Comment by jpbro** [comment]
Complete in commit https://github.com/jpbro/VbPcre2/commit/0703cf8fef462de5b380ecec3b3dfabc0cdde623

**Comment by dragokas** [comment]
Congratulations! :)

**Comment by jpbro** [comment]
Thanks :) Sorry it too so long!

I guess I'm ready for your pull request for your much improved test front end now ;)
