### ISSUE TITLE
Should/can we statically link pcre-16.dll and VBPCRE2.dll?

### ISSUE THREAD

**Issue by jpbro** [jpbro/VbPcre2#25]
@wqweto [brought up a point that I think deserves some public discussion](http://www.vbforums.com/showthread.php?847611-RESOLVED-Regular-expressions-VBScript-Regexp-alternatives-(PCRE)&p=5289257&viewfull=1#post5289257)

The main question is: why are pcre-16.dll and VBPCRE2.dll separate, and would there be an advantage to statically linking them?

Personally, I don't think there's a huge advantage to linking them since we already have to ship one external DLL (so what's the problem with shipping two). That said, I'm not against linking them if the community disagrees with me and would prefer to have a single DLL.

The issues as I see it are:

- How do we link the two DLLs? I've never done this, so I would appreciate some input.

- If we can link them, can we automate this so I don't have to manually perform a bunch of steps to link them every time I rebuild one of the DLLs?

- PCRE2 is BSD licensed, while VBPCRE2 is MIT licensed - is there any conflict linking libraries with those 2 different licenses, or are there any special steps I'd have to take re: releasing source/configuration files that perform the link?

I appreciate any input!

**Comment by wqweto** [comment]
I had some success [staticly linking sqlite](https://github.com/wqweto/vbsqlite) into a VB6 ActiveX DLL. This requires some initial effort to produce VB6 stubs for debug and C/C++ trampolines that replace in release these VB6 stubs at link-time.

It also requires a custom (transparent) linker that recognizes `.cobj` files in target folder and swaps VB6 compiled modules surreptitiously.

In the case of vbsqlite repo these `.cobj` files are produced from`lib` folder's `build.bat`. The VB6 `.dll` is compiled as usual from the IDE.

I have no idea about the licenses but suppose VB6 effort is much easier to re-license if needed.

**Comment by jpbro** [comment]
Hi Vladimir, thank you for the link to your statically linked SQLite project - looks very interesting. I'm studying it now.

**Comment by dragokas** [comment]
Hi, Jason!

Can I ask you please redirect my request to vbforums.com feedback for admin?
Sorry for offtopic, I don't have another contact.

```
I can't login because forum doesn't accept my password.

I can't reset password, because:

----------------

Sadly, you’ve reached a page that can’t be displayed.

We’ve logged this action, so we are aware there is an issue!

At this time, please hit your browser’s back button or simply close this page!

The incident ID is: N/A. 
Event id: 465060899388

-------------------

I can't register new account because:

-------------------

Sadly, you’ve reached a page that can’t be displayed.

We’ve logged this action, so we are aware there is an issue!

At this time, please hit your browser’s back button or simply close this page!

The incident ID is: N/A. 
Event id: 465081989695

--------------
My IP is 185.195.9.xxx (Ukraine)
nickname: dragokas

```
thanks!

**Comment by jpbro** [comment]
Hi Stanislav, I've set an email to the vbforums admins, hopefully they can help soon!
