### ISSUE TITLE
Office 365 64-bit. "Class not Registered"

### ISSUE THREAD

**Issue by mindflux** [jpbro/VbPcre2#27]
I imagine this is probably a bitness issue?  I downloaded the vbpcre2.dll and put it in C:\windows\syswow64 (also tried system32) and registered the dll.

DLL shows up as a reference in VBA and intellisense picks up on it just fine, but trying to run any code gives me a class not registered message even just trying to set .options.compile.casesensitive = false
Example code:

```
  Public Function Rx(p As String, s As String) As Boolean
      Dim r As New cPcre2
      Dim x As cPcre2Matches
  
      With r.Options.Compile
          .CaseSensitive = False
      End With
      
      Set x = r.Match(s, p)
      
      Debug.Print x.text
  
  End Function
```

**Comment by jpbro** [comment]
Unfortunately AFAIK you can't use 32-bit DLLs directly in 64-bit host applications. One possibility would be to create a 32-bit out-of-process server to wrap the DLL, but that can be a lot of work.

**Comment by jpbro** [comment]
Here's an article about creating 32-bit out-of-process servers for use with 64-bit apps: https://blog.mattmags.com/2007/06/30/accessing-32-bit-dlls-from-64-bit-code/

**Comment by mindflux** [comment]
Alright, thanks for confirming. It's a shame Microsoft hasn't updated or replaced the vbscript regex.
