### ISSUE TITLE
Was MIT the right license for VBPCRE2?

### ISSUE THREAD

**Issue by jpbro** [jpbro/VbPcre2#3]
I'm relatively inexperienced with Open Source licenses - I wanted the VBPCRE2 license to be as permissive as possible, and GitHub recommended the MIT license when I created the repository. Any opinions on whether or not this was the right choice? Should I/can I change it if there's a consensus on a better choice?

Thanks in advance for any feedback!

**Comment by dragokas** [comment]
PCRE is BSD.

AFAIK, MIT + no ads = BSD, so BSD is more restrictive,
where "no ads" mean, that users have no rights to use your name or name of PCRE's author to promote their own products.

**Comment by tannerhelland** [comment]
Yes, what @dragokas said!  MIT and BSD are roughly interchangeable, depending on which BSD license you use.  (There are multiple BSD licenses, and PCRE uses the "BSD 3-clause" version, which has an extra "don't use the creator's name to advertise your product" clause.  Other than that it is nearly identical to MIT.)

For small development teams not officially sponsored by a company (e.g. this project!), the "no advertising" clause doesn't make much sense, so the BSD 2-clause or MIT licenses are both excellent choices.  The MIT-license is fully compatible with the BSD license used by the parent project, so you are absolutely fine to use it.

**Comment by jpbro** [comment]
Thanks for the education @dragokas and @tannerhelland! MIT looks like an acceptable choice, and I'll consider the issue resolved.
