### ISSUE TITLE
Bad line breaks

### ISSUE THREAD

**Issue by dragokas** [jpbro/VbPcre2#4]
It seems when you uploaded a project, your Git somehow replaced CrLf by Lf in all source files.
My VB6 IDE refuse loading this project.

**Comment by dragokas** [comment]
he-he, fixed by regexp in Akelpad:
([^\r])\n
\1\x0d\x0a

It remains to understand where it broke during the uploading.

**Comment by jpbro** [comment]
Strange, not sure what might be wrong (obvious a Windows <> Linux line ending issue, but not sure why it would be happening). I've been able to get Tanner's merge fine, and I've even forked other projects like vbWIdgets and PhotoDemon without an issue with line breaks. I'll see what I can find out., thanks for reporting the problem.

**Comment by nouba** [comment]
You should ceate a **.gitattributes** file like in [Using Git with VB6](https://stackoverflow.com/questions/2462480/using-git-with-vb6) mentioned.

**Comment by jpbro** [comment]
Hi nouba, thanks for your advice - I've added a .gitattributes and .gitignore file as per the link you sent, so let's hope that works! @dragokas - can you confirm if there's any improvement?

**Comment by tannerhelland** [comment]
@dragokas - line-endings can be set on a per-repository basis, but on Windows it is also helpful to set your "global" git settings to auto-detect vbCrLf.  This makes it easier to work with repositories that don't specify a linebreak char.

From a Git-enabled command line, you can type:

`git config --global core.autocrlf true`

This is helpful if you work on projects from multiple OSes, or if you have collaborators working from a different OS than you.

**Comment by dragokas** [comment]
@jpbro, confirmed. Project is loaded ok.
@tannerhelland, thanks. It's a good solution.
Oh, just noticed, that 2 of all my files in my HiJackThis repository also cannot be loaded (Lf). However, I never deal with linux utilities. I'll take up arms your solution too.

**Comment by jpbro** [comment]
Thanks for reporting back @dragokas,, glad everything is working now re: linebreaks.
