### ISSUE TITLE
Need Better Handling/Reporting of PCRE2 Error Codes

### ISSUE THREAD

**Issue by jpbro** [jpbro/VbPcre2#7]
Note to self - add descriptive messages for the full PCRE2 error code list.

**Comment by tannerhelland** [comment]
Apologies if you already saw this, but you may be able to sidestep this issue entirely by using `pcre2_get_error_message()` to translate error IDs into human-readable messages:

http://www.pcre.org/current/doc/html/pcre2_get_error_message.html

**Comment by jpbro** [comment]
Duh! I must admit I've been approaching this thing a bit loosely - not reading the entire PCRE2 docs first, and just bumbling along willy-nilly. Part of that is how I like to learn by doing vs. studying, but that approach does expose embarrassments like this :blush: 
Anyway @tannerhelland there's never any need to apologize for pointing out this kind of correctness to me, and thanks for doing it!

**Comment by tannerhelland** [comment]
Bumbling along willy-nilly is my favorite development strategy!  :)  (In all seriousness, I think it's the only way to figure out complex libraries like this one...)

The API table of contents also had a typo next to this function, describing its purpose as "Free study data" which is definitely not correct.  I think the actual function page is correctly documented, however.

**Comment by jpbro** [comment]
Hi Tanner - sorry for the delayed response, the power was out all day yesterday while some infrastructure was being upgraded. I'll leave the issue open until I've implemented pcre2_get_error_message in the wrapper, but thanks again for pointing it out.

**Comment by jpbro** [comment]
I've wrapped `pcre2_get_error_message` now and it's being used to supply additional information in the error handler for the Replace and Execute2 methods (Execute2 is a private method that is called by the public Test and Execute methods since they share code). Thanks again @tannerhelland!
